### ISSUE TITLE
Será que rola alterar o css dessa página ?

### ISSUE THREAD

**Issue by ghost** [artursantiago/css-journey#1]
https://source55.github.io/PullRequests/

Será que rola alterar o css dessa página ?
Implementar umas melhorias, sei lá...
Talvez alterar a cor do background da página e a cor do bg dos box.
E as bordas.
E também as fonts...

**Comment by artursantiago** [comment]
Opa Rodrigo, blz?
Não entendi muito bem, vc quer que eu te ajude com o layout do seu site?

**Comment by ghost** [comment]
Eu escrevi porque entendi que voce tava escrevendo codigo css pra esse seu projeto. Dai sugeri que vc escrevesse codigo css praquele link que eu enviei.
escrever css praquela pagina sendo essa tarefa parte do seu projeto...

**Comment by artursantiago** [comment]
Fala man, então...
Fazer o layout da tua página não vai rolar, mas se tu quiser fazer algo parecido com o meu, da uma olhada na estilização da home, eu estilizo cards que parecem com o que vc tem no seu site.
Qualquer dúvida pode me chamar lá no linkedin https://www.linkedin.com/in/artursantiago/
